# Interval to check new mail upon.
mail_poll_interval: "30s"
mail_poll_task_timeout: "30s"

# Forwarders configuration contains list of notifier backends.
# Currently only Telegram email notification backend is supported.
forwarders:
  telegram:
    bot_token: "tg_bot_token"
    web_app_url: "your_tg_web_app_url"

# Possible values: 'DEBUG', 'INFO', 'WARN', 'ERROR'.
log_level: "INFO"

clients:
  - proto: "imap"
    address: "your.imap.server.com:993"
    login: "your.login@mail.com"
    password: "your.password"
    # Not supported yet.
    include_attachments: false
    # Maximum attachments size to process.
    maximum_attachment_size: "50M"
    # Not supported yet.
    include_images: false
    # Custom filters could be specified per each client.
    filters: []
    contact_points:
      - type: "telegram"
        tg_chat_id: your_chat_id
        silent_mode: true # Sends messages in silent mode (Optional, defaults to 'false').
        disable_forwarding: true # Forbid to forward messages sent by bot (Optional, defaults to 'false').
        # Mode for parsing entities in the message text (Optional).
        # Possible values: '', 'HTML', 'MarkdownV2', 'Markdown'. 
        # Defaults to 'MarkdownV2' 
        parse_mode: "MarkdownV2" 
        # Custom message template (Optional). If not specified, default one is used.
        # For templating standard Go template engine is used.
        # Refer to: https://pkg.go.dev/text/template
        template: |
          {{- define "addresses" -}}
            {{- range $idx, $address := . -}}
              {{ $escapedAddress := escapeMarkdown $address.Address }}

              {{- if ne $idx 0 -}}
                {{- printf ", " -}}
              {{- end -}}

              {{- printf "[%s](mailto://%s)" $escapedAddress $address.Address -}}
            {{- end -}}
          {{- end -}}

          {{- if .From }}*From*: {{ template "addresses" .From }}
          {{ end }}
          {{- if .To }}*To*: {{ template "addresses" .To }}
          {{ end }}
          {{- if .ReplyTo }}*Reply To*: {{ template "addresses" .ReplyTo }}
          {{ end }}
          {{- if .CC }}*CC*: {{ template "addresses" .CC }}
          {{ end }}
          {{- if .BCC }}*BCC*: {{ template "addresses" .BCC }}
          {{ end }}
          {{- if .Subject }}*Subject*: {{ escapeMarkdown .Subject }}
          {{ end }}
          {{- if .Date }}*Date*: {{ .Date.Format "Jan 02 2006 15:04:05" }}
          {{- end }}

          {{ range $part := .BodyParts }}
            {{- if eq $part.MIMEType "text/plain" }}
              {{- bytestring $part.Body | escapeMarkdown }}
            {{- else -}}
              MESSAGE CONTENT COULD NOT BE REPRESENTED
            {{ end }}
          {{ end }}
