name: chatmailer

services:
  chatmailer:
    container_name: chatmailer
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
      - ./config.yaml:/etc/chatmailer/config.yaml
    command: "-config /etc/chatmailer/config.yaml"
    ports:
      - "8080:8081"
