name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  run:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 3
    continue-on-error: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true

      - name: Lint
        uses: golangci/golangci-lint-action@v6.5.0
        with:
          version: latest
          args: --timeout 3m
